; Listing generated by Microsoft (R) Optimizing Compiler Version 14.00.50727.42 

	TITLE	c:\dig\dbg\author\code\chap24\VC8Win32\stdafx.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB OLDNAMES

PUBLIC	___@@_PchSym_@00@UwrtUwytUzfgsliUxlwvUxszkCEUexIdrmDCUivovzhvUhgwzucOlyq@
___@@_PchSym_@00@UwrtUwytUzfgsliUxlwvUxszkCEUexIdrmDCUivovzhvUhgwzucOlyq@ DD 01H DUP (?)
END
